---
- name: Update VM
  hosts: all

  tasks:
    - name: Mettre à jour le cache APT
      become: yes # Exécuter toutes les tâches avec les privilèges root (sudo)
      ansible.builtin.apt:
        update_cache: yes
      tags:
        - apt_update

    - name: Mettre à niveau tous les paquets installés
      become: yes # Exécuter toutes les tâches avec les privilèges root (sudo)
      ansible.builtin.apt:
        upgrade: yes
      tags:
        - apt_upgrade
