---
- name: Install docker, if needed, then reboot
  hosts: VM, LXC


  tasks:
    - name: Check Docker instrallation
      command: docker --version
      register: docker_check
      ignore_errors: yes

    - name: Display if exist
      debug:
        msg: "Docker installed"
      when: docker_check.rc == 0

    - name: Display if not exist
      debug:
        msg: "Docker not installed"
      when: docker_check.rc != 0

    - name: Install Docker
      become: yes
      when: docker_check.rc != 0
      block:
        - name: Installer les prérequis pour Docker
          ansible.builtin.apt:
            name:
              - ca-certificates
              - curl
            state: present

        - name: Créer le répertoire /etc/apt/keyrings
          ansible.builtin.file:
            path: /etc/apt/keyrings
            state: directory
            mode: '0755'

        - name: Télécharger la clé GPG officielle de Docker
          ansible.builtin.get_url:
            url: https://download.docker.com/linux/ubuntu/gpg
            dest: /etc/apt/keyrings/docker.asc
            mode: '0644'

        - name: Ajouter le dépôt Docker aux sources APT
          ansible.builtin.apt_repository:
            repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
            state: present
            filename: docker
            update_cache: yes

        - name: Ajouter le dépôt Docker aux sources APT
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
            state: present
            filename: docker
            update_cache: yes

        - name: Installer les paquets Docker
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            state: present

        - name: S'assurer que le groupe 'docker' existe
          ansible.builtin.group:
            name: docker
            state: present

        - name: Ajouter l'utilisateur courant au groupe 'docker'
          ansible.builtin.user:
            name: "{{ ansible_user_id }}"
            groups: docker
            append: yes
          notify: Redémarrer la session utilisateur (Docker)

      tags:
        - docker

    - name: Reboot
      import_tasks : "99_reboot.yml"
      when: docker_check.rc != 0
