---
- name: Mettre à niveau les VMs et configurer SSH/Docker
  hosts: all

  tasks:
    - name: Update VM
      import_tasks : "01_update.yml"

    - name: Update .bashrc
      import_tasks : "02_configSh.yml"

    #create Snapshot on proxmox

    - name: Harden ssh
      import_tasks : "03_ssh.yml"

    #create Snapshot

    - name: Install docker
      import_tasks : "04_dockerInstall.yml"

    #create Snapshot afterSnapshot
